bob/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required # NOQA
from .views import task, filedownload, index

app_name = 'bob'
urlpatterns = [
    path('', index.LoginView.as_view(), name='login'),
    path('index', login_required(index.IndexView.as_view()), name='index'),
    path('<str:task_name>/gogo/', task.GogoView.as_view(), name='gogo'),
    path('<str:task_name>/bobtasks/', login_required(task.BobTaskView.as_view()),
         name='bobtasks'),
    path('<str:task_name>/bobtasks/plain/<int:status>/',
         task.BobTaskPlainView.as_view(), name='bobtasks_plaintext'),
    path('<str:task_name>/bobtasks/<int:id>/',
         csrf_exempt(task.BobTaskUpdateView.as_view()), name='bobtasks_update'),
    path('fileload/<str:task_name>/<str:in_out>/<str:filename>/',
         filedownload.file_download, name='file_download'),
]

bob/templates/bob/bobtask.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
	<title>BOBTASKS</title>
	<!-- CSS only -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

   <!-- JS, Popper.js, and jQuery -->
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>

<table class="table table-striped">
	<caption>{{ name }}</caption>
   <thead>
      <tr>
         <th>Task-paras</th>
         <th>Task-status</th>
         <th>Task-udate</th>
         <th>Task-input-file</th>
         <th>Task-output-file</th>
         <th>Task-output</th>
      </tr>
   </thead>
   <tbody>
   {% for task in tasks %}
      <tr>
         <td>{{ task.para }}</td>
         <td>{{ task.status }}</td>
         <td>{{ task.udate }}</td>
         <td>{{ task.input_file }}</td>
         {% if task.output_file %}
            <td><a href="{% url 'bob:file_download' name 'output' task.output_file %}">{{ task.output_file }}</a></td>
         {% else %}
            <td>{{ task.output_file }}</td>
         {% endif %}
         <td>{{ task.output }}</td>
      </tr>
   {% endfor %}
   </tbody>
</table>

</body>
</html>

bob/templates/bob/index.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8"> 
	<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <ul id="myTab" class="nav nav-tabs">
 {% for name in all_names %} 
 <li class="dropdown"><a href="#{{ name }}" data-toggle="tab">{{ name }}</a></li>
 {% endfor %}
</ul>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div id="myTabContent" style="padding: 100px 100px 10px;">
 {% for t in all_t %}  
	<div class="tab-pane fade" id="{{ t.current_name }}">
    <form action="{% url 'bob:gogo' t.current_name %}" method="post" 
          enctype="multipart/form-data" accept-charset="utf-8" role="form">
     {% csrf_token %}
     {% for field in t.current_fields %}
      <div class="form-group">
        <label for="name">{{ field }}</label>
        <input type="text" name="{{ field }}" />
      </div>
      {% endfor %}
      <div class="input-group">
        <input type="file" name="input-file" class="form-control">
      </div>
      <br>
      <button type="submit" class="btn btn-primary">保存</button>
    </form>
    <br>
    <a href="{% url 'bob:bobtasks' t.current_name %}">view tasks</a>
  </div>
 {% endfor %}
</div>

</body>
</html>

bob/templates/bob/login.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<html>
<head>
     <title>登录</title>
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   	 <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	   <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	   <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
     <h1 class="page-header">登 录</h1>
     <form action="{% url 'bob:login' %}" method="post" class="form-horizontal">
     {% csrf_token %}
        <div class="form-group" >
           <div class="col-sm-5">
              <input type="text" class="form-control" placeholder="请输入用户名" name="username"/>
           </div>
        </div>
        <div class="form-group" >
           <div class="col-sm-5">
              <input type="password" class="form-control" placeholder="请输入密码" name="password"/>
           </div>
        </div>
        <div class="form-group" >
           <div class="col-sm-5">
              <button class="btn-primary">登 录</button>
           </div>
        </div>
     </form>
</body>
</html>